### ISSUE TITLE
buy iotabot to join the group

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-Chatbox#181]

**Comment by zkk333** [comment]
先关掉吧，看后续是否需要改了，给它加个权重

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/f6c8d0d9-9261-477c-ac2d-58c8a75f040d)

**Comment by zkk333** [comment]
这个关掉吧 现在是群名的名称
