### ISSUE TITLE
禁言这块还是不太对，满分100，被1个用户禁言了，竟然还是100分 ---（貌似确实有点问题，详见内容）

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-Chatbox#192]
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/025b2d38-cfff-4720-9b70-639bc8cf511e)

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/e05af3af-8f7e-4f26-9a2e-206df4c4f7a2)

这个用户被禁言过一次，但是接口返回的竟然是被0人禁言
https://prerelease.api.iotacat.com/api/groupfi/v1/testreputation?groupId=0x7c30cbddd45dcd87471426e7544997c04b56ab834d666094cb2a92efd67bd1ef&address=smr1qq902e9mvknfghtghs8g7y6q27rmyjs9kexv9mv5qu3ms9galt30c340qxe

**Comment by zkk333** [comment]
这个没出现过了  mm上测试是ok的，先关掉
