### ISSUE TITLE
偶尔出现消息推送失败的问题(猜测可能原因：长时间（不好判断）停留在聊天对话页面) 1、后续退回上级页面，重新进入聊天页面 消息就会显示 2、即使重新进入聊天页面 消息也不会显示。清缓存后才行  --得等段时间看效果

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-Chatbox#193]

**Comment by zkk333** [comment]
额 确实有问题 a地址发的消息 两个地址全部清完缓存后，a消息虽然还在，但是b依然没看到消息。。。

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/226f4534-0c06-4998-a718-1c3e2a5c752c)



![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/9d34b9f0-30eb-4d01-b9f8-ddb2d12eec14)

**Comment by tanglepay-dev** [comment]
need more repro steps

**Comment by zkk333** [comment]
这个貌似没出现过了  先关掉，复现在开
