### ISSUE TITLE
清完缓存后，当一个地址加载完所有聊天记录后，切换到另一个地址，不会自动加载聊天记录，需要刷新页面才会加载。。

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-Chatbox#209]
看看这个能不能解决。

![Image](https://github.com/TanglePay/GroupFi-Chatbox/assets/7235117/f572ea09-0426-4d9b-8a1c-98dc10a05b70)

**Comment by zkk333** [comment]
有时候得多次刷新 才会加载聊天记录

**Comment by zkk333** [comment]
暂时没问题
