### ISSUE TITLE
当一个新用户再翻看聊天记录的时候，且这时候没有人发消息的话，返回到列表页面，列表页面显示的消息不是当前群组的最新消息

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-Chatbox#211]
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/c4fd5cff-05cb-4e3f-87b4-f227481456a9)

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/83eb3c88-1b6f-4d59-b086-df207ee66766)

**Comment by zkk333** [comment]
测试通过
