### ISSUE TITLE
GroupFI-SDK encrypts the message with X and sharedoutput

### ISSUE THREAD

**Issue by tanglepay-dev** [TanglePay/GroupFi-Chatbox#352]

**Comment by time-endless** [comment]
需求理解： sharedOutput 里会存放 recipients 列表，recipients 列表需要加密存储，加密过程要用到每个成员的 publicKey。

**Comment by time-endless** [comment]
更正理解：
每个群有个公共加密的密码子T，这个T只能群成员知道。
群里的消息都是用T加密的，只能群成员看见（能解密），外部人看不见。
---------------------------
sharedoutput干的事是，是让每个群成员能去获得T。
具体来说，
用每个群成员的公钥去加密一次T。把这一整个信息存到这个所谓的sharedoutput里。
这样每个群成员可以用自己的私钥都解密出T。
解密出T就可以看群里消息了。

**Comment by zkk333** [comment]
已上线一个版本
