### ISSUE TITLE
groupfi 上接入 trollbox 有个 非常奇怪的 bug， 如图：

### ISSUE THREAD

**Issue by time-endless** [TanglePay/GroupFi-Chatbox#362]
Dapp 连接钱包的时候，如果 TP 里是 evm 地址，之后快速断开连接，有几率会出现图中的错误，gropufi页面会完全卡住，没反应

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/138768192/9d633c8b-4837-45f5-85c2-3db42e7f8178)

**Comment by zkk333** [comment]
测试通过
