### ISSUE TITLE
trollbox右侧贴到网站最右以及最下

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-Chatbox#372]
整体目标： 使trollbox的展示不要喧宾夺主。

1/ 右侧几乎不留间隙，类似于图中的模式
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/2378bb4d-d09b-4255-a39f-925ceabb15f5)

2/ trollbox展示时，调整收起按钮样式。
    1）从底部的大按钮变更为右上角的按钮，见设计稿（下面有截图）
    2）底部也贴到页面最下方

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/5b2fc881-167f-4998-9d04-c717bff1e8b3)

**Comment by theuniverse** [comment]
PR created: https://github.com/TanglePay/GroupFi-trollbox/pull/384

@time-endless Please help review and deploy to testing environment for review. :)

**Comment by zkk333** [comment]
测试通过
