### ISSUE TITLE
增加显示信息来源网站

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-Chatbox#396]
1/ 消息体中，增加来源网站的信息。
可以看到每个用户这条信息是从哪个网站发出来的。样式见设计稿。

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/3c904094-fa9f-48c1-b0ac-fb67c62bc795)

2/ 目前消息体中的时间原则是靠消息框的最右。但这个最右之前的实现只考虑了消息内容本身的最后，要调整成也要考虑用户名所在行的长度。如图示。
增加了信息的来源网站后，当消息短时，时间与展示的网站信息末端对齐。

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/6718b81b-7fd2-42b5-8a14-6c76f4161e5d)
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/45634a7c-700b-4772-9c84-01c1c1e7072a)

**Comment by theuniverse** [comment]
需要在Message的数据结构中得到支持，re-assign给 @time-endless ：）

**Comment by zkk333** [comment]
测试通过
