### ISSUE TITLE
evm groupfi-- 当新用户首次get smr时，当smr的金额小于10（应该是），会处在一直转圈圈的环节，看如何优化下，见截图

### ISSUE THREAD

**Issue by zkk333** [TanglePay/GroupFi-Chatbox#439]
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/b4d8c8fb-ea38-44dd-99ba-85cf1f01d154)

**Comment by zkk333** [comment]
看设计图上 -当低于10smr时，前端会提示不能低于10smr，见截图

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/f88148a4-0ed8-4284-8752-9161279e92a3)

**Comment by time-endless** [comment]
这个提示加了，不过样式还有点问题，麻烦Qi 帮忙看看了。
然后一直 loading 的问题也修复了

**Comment by zkk333** [comment]
测试通过
