### ISSUE TITLE
evm groupfi--metamask上--新地址--点击mark后 页面显示mark成功了，但是等1-2分钟后，再次进入群聊，还是未mark的状态，一直没有mark成功 

### ISSUE THREAD

**Issue by zkk333** [TanglePay/GroupFi-Chatbox#445]

**Comment by zkk333** [comment]
卧槽 ，忽然可以了 先关掉  再出现再打开

**Comment by zkk333** [comment]
再次打开  逆天的地方来了  metamask下有个地址一直mark不成功，其他都能成功，目前来看这个私钥必现 ba061bd9a372cf698f70cdb47a0344398b5468acd1ab7bc55fc1425ac0e583c0

**Comment by zkk333** [comment]
好几个地址必现  我是看不出来啥问题

**Comment by alexmengyuan** [comment]
mark vote 和 mute 有output在不同proxy address的现象，和郭维一起处理了下哈

**Comment by zkk333** [comment]
测试通过
