### ISSUE TITLE
疑问--这个位置是需要跟设计图保持一致吗，带proxy mode地址，还有一个聊天详情页面，聊天后缀是否带来自哪个平台  还是说以后做

### ISSUE THREAD

**Issue by zkk333** [TanglePay/GroupFi-Chatbox#463]
![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/048d3ba1-39c0-4709-abec-686a19aa9d36)

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/21ea2594-6a96-4eb8-9394-a923ef987927)

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/1aa19c4f-bcd3-44a5-abfc-a0eb17f09c11)

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/42662926/0cfa1cab-690c-45ae-bb79-54d8cdc4e54a)

**Comment by shiva01** [comment]
不用这个设计，用另一版设计，是@符号。这个我单独给qi开过git的issue
