### ISSUE TITLE
创建账户流程文案补充

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-Chatbox#559]
创建新账户的流程；老账户获取X的流程

1）先修改等待时间，加上相应的文案
Creating account...
Signing...
Registering account on chain...
Connecting...

![Image](https://github.com/TanglePay/GroupFi-trollbox/assets/7235117/d891719d-7589-4b9d-85e4-573eef56434e)

**Comment by zkk333** [comment]
测试通过
