### ISSUE TITLE
浏览模式的优化1

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-Chatbox#591]
1. 目前浏览模式，看不到群成员。
群成员信息与登陆状态无关，应该能看到

2. 浏览模式，目前也看不到群的头像，应该和第一个是同一个问题

3. 浏览模式进一步把“my groups”也隐藏掉，仅保留for me。（浏览模式下并不存在my groups）

**Comment by zkk333** [comment]
测试通过
