### ISSUE TITLE
被禁言后，无法聊天的时候，点击聊天框，一直转圈圈，见视频，建议无法点击吧 还是？

### ISSUE THREAD

**Issue by zkk333** [TanglePay/GroupFi-Chatbox#624]
https://github.com/TanglePay/GroupFi-Chatbox/assets/42662926/577718ca-c6a7-4553-abf2-8c6bf95da6b9

**Comment by shiva01** [comment]
这块的提示语，除非另有设计，都先做成不可点击

**Comment by zkk333** [comment]
测试通过
