### ISSUE TITLE
多钱包支持

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-Chatbox#632]
1. 除了metamask，groupfi支持下另外几种常见钱包：
trust wallet（binance出的）
okx wallet
coinbase wallet
等支持evm的接口与metamask完全一样的钱包。
2. 用户使用chatbox存在几种情形：
未连钱包： 浏览模式
连了支持的钱包：正常使用
连了不支持的钱包：提示“Chatbox does not support this wallet yet.” （如果识别不出来，显示浏览模式）

**Comment by zkk333** [comment]
测试通过，不过需求2 暂时无法测试，不支持的钱包压根都不出现在连接的列表
