### ISSUE TITLE
register/connect页样式调整

### ISSUE THREAD

**Issue by shiva01** [TanglePay/GroupFi-Chatbox#679]
1. 1）如图（应该是设计稿中的第二个），但把把替换成设计稿8种的静态猫。
   2）右下角的Powered by groupfi.ai是超链接 
2. connect（登陆）页面与register页面基本相同。1）主按钮不同 2）没有browse as a guest按钮
3. 顺带将个人信息页的Powered by groupfi.ai调整成统一的新样式（见图）
![Image](https://github.com/TanglePay/GroupFi-Chatbox/assets/7235117/f6fd99fb-3af0-4d73-b0d4-29d82694a298)
![Image](https://github.com/TanglePay/GroupFi-Chatbox/assets/7235117/9464ef2c-991b-4341-8048-1130b253e989)

**Comment by zkk333** [comment]
测试通过
